# Generated by Django 5.2.7 on 2025-10-14 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('injection', 'Investitsiya kiritish'), ('withdrawal', 'Pul yechish')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('channel', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], default='cash', max_length=10)),
                ('withdrawal_source', models.CharField(blank=True, choices=[('profit', 'Foydadan'), ('capital', 'Kapitaldan')], help_text='Foydadan yoki kapitaldan?', max_length=10)),
                ('memo', models.TextField(blank=True, help_text='Sabab yoki izoh')),
                ('is_approved', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_transactions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'created_at'], name='finance_cap_type_0d2ecd_idx'), models.Index(fields=['store', 'created_at'], name='finance_cap_store_i_0855d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_opening', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_opening', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_closing', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_closing', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['store', 'date'], name='finance_cas_store_i_563b0f_idx')],
                'unique_together': {('store', 'date')},
            },
        ),
    ]
