# Generated by Django 5.2.7 on 2025-10-22 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_capitaltransaction_cashbalance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='journalline',
            name='finance_jou_account_93f75b_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalline',
            name='finance_jou_object__e19242_idx',
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['object_app', 'object_model', 'object_id', 'account'], name='jl_obj_acc_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('object_app', ''), _negated=True), models.Q(('object_model', ''), _negated=True), models.Q(('object_id', ''), _negated=True)), fields=('object_app', 'object_model', 'object_id', 'account'), name='uniq_post_per_object_per_account'),
        ),
    ]
