# Generated by Django 5.2.7 on 2025-10-22 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0003_remove_journalline_finance_jou_account_93f75b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashbalance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cashbalance',
            name='store',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='journalline',
            name='uniq_post_per_object_per_account',
        ),
        migrations.RemoveIndex(
            model_name='capitaltransaction',
            name='finance_cap_type_0d2ecd_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalline',
            name='jl_obj_acc_idx',
        ),
        migrations.RemoveField(
            model_name='capitaltransaction',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='capitaltransaction',
            name='withdrawal_source',
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='capitaltransaction',
            name='direction',
            field=models.CharField(blank=True, choices=[('cash_to_card', 'Naqd → Karta'), ('card_to_cash', 'Karta → Naqd')], help_text='Faqat transfer uchun', max_length=20),
        ),
        migrations.AddField(
            model_name='capitaltransaction',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('asset', 'Aktiv'), ('liability', 'Majburiyat'), ('equity', 'Kapital'), ('revenue', 'Daromad'), ('expense', 'Xarajat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='capitaltransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_capital_txns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capitaltransaction',
            name='channel',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('both', 'Ikkala')], max_length=10),
        ),
        migrations.AlterField(
            model_name='capitaltransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_capital_txns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capitaltransaction',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capitaltransaction',
            name='type',
            field=models.CharField(choices=[('injection', 'Investitsiya'), ('withdrawal', 'Yechish'), ('transfer', "O'tkazma")], max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='memo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Debit = musbat, Credit = manfiy', max_digits=12),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='object_app',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='object_model',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['category', 'code'], name='finance_acc_categor_41e2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='capitaltransaction',
            index=models.Index(fields=['type', 'is_approved', 'created_at'], name='finance_cap_type_102730_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date', '-created_at'], name='finance_jou_date_c2923a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['ref'], name='finance_jou_ref_d8186a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['entry', 'account'], name='finance_jou_entry_i_f0a199_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['object_app', 'object_model', 'object_id'], name='finance_jou_object__e19242_idx'),
        ),
        migrations.DeleteModel(
            name='CashBalance',
        ),
    ]
