# Generated by Django 5.2.7 on 2025-10-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_cashbalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitaltransaction',
            name='withdrawal_source',
            field=models.CharField(blank=True, choices=[('profit', 'Foydadan'), ('capital', 'Kapitaldan')], help_text='Faqat withdrawal uchun - foydadan yoki kapitaldan', max_length=20),
        ),
    ]
