user  nginx;
worker_processes  auto;

events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    sendfile      on;
    server_tokens off;

    # gzip (ixtiyoriy)
    gzip on;
    gzip_comp_level 5;
    gzip_types text/plain text/css application/json application/javascript application/xml image/svg+xml;

    include /etc/nginx/conf.d/*.conf;
}
