# Generated by Django 5.2.7 on 2025-10-23 11:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RemoveField(
            model_name='store',
            name='slug',
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maksimal tasdiqlash summasi. 0 = cheksiz (faqat owner uchun)', max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_stores',
            field=models.ManyToManyField(blank=True, help_text="Qaysi do'konlar uchun tasdiqlash huquqi bor", related_name='approvers', to='accounts.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_commissions',
            field=models.BooleanField(default=False, help_text="Komissiyalarni tasdiqlash va to'lash huquqi"),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_consignment',
            field=models.BooleanField(default=False, help_text="Konsignatsiya to'lovlarini tasdiqlash huquqi"),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_expenses',
            field=models.BooleanField(default=False, help_text='Xarajatlarni tasdiqlash huquqi'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_transactions',
            field=models.BooleanField(default=False, help_text='Sotuvlarni va boshqa tranzaksiyalarni tasdiqlash huquqi'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='delegated_at',
            field=models.DateTimeField(blank=True, help_text='Huquq berilgan sana', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='delegated_by',
            field=models.ForeignKey(blank=True, help_text='Huquqni bergan shaxs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='delegation_note',
            field=models.TextField(blank=True, help_text='Nima uchun huquq berilgani haqida izoh'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('seller', 'Seller')], default='seller', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.store'),
        ),
        migrations.AlterModelTable(
            name='store',
            table='stores',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
