# Generated by Django 5.2.7 on 2025-10-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_store_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="Keyingi kirishda parolni o'zgartirishi shart"),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text="Oxirgi parol o'zgartirish sanasi", null=True),
        ),
    ]
