# Generated by Django 5.2.7 on 2025-10-24 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password_user_password_changed_at'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'verbose_name': "Do'kon", 'verbose_name_plural': "Do'konlar"},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='approval_limit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_stores',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_approve_commissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_approve_consignment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_approve_expenses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_approve_transactions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delegated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delegated_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delegation_note',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_changed_at',
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name="Do'kon nomi"),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name="Parolni o'zgartirish majburiy"),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Ega'), ('seller', 'Sotuvchi')], default='seller', max_length=10, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.store', verbose_name="Do'kon"),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active', 'name'], name='accounts_st_is_acti_1d8785_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['store', 'role'], name='accounts_us_store_i_1ac718_idx'),
        ),
        migrations.AlterModelTable(
            name='store',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
