# Generated by Django 5.2.6 on 2025-09-21 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('imei_full', models.CharField(max_length=20, unique=True)),
                ('imei_last4', models.CharField(db_index=True, max_length=4)),
                ('has_documents', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('defect', models.CharField(blank=True, max_length=120)),
                ('battery_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ownership', models.CharField(choices=[('owned', 'Owned'), ('consignment', 'Consignment')], max_length=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consignment_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('owner_name', models.CharField(blank=True, max_length=80)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_repair', 'On Repair'), ('sold', 'Sold')], default='available', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.batchintake')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.brand')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.color')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.modelname')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stores/%Y/%m/%d')),
                ('kind', models.CharField(choices=[('doc', 'Document'), ('cond', 'Condition'), ('other', 'Other')], default='other', max_length=8)),
                ('is_primary', models.BooleanField(default=False)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'imei_last4'], name='inventory_p_store_i_4e01b7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'model', 'status', 'created_at'], name='inventory_p_brand_i_4e85a6_idx'),
        ),
    ]
