# Generated by Django 5.2.6 on 2025-09-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_store_i_4e01b7_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imei_last4',
        ),
    ]
