# Generated by Django 5.2.6 on 2025-09-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_inventory_p_store_i_4e01b7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchintake',
            name='count',
        ),
        migrations.AddField(
            model_name='batchintake',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='batchintake',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
