# Generated by Django 5.2.6 on 2025-09-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imei_last4',
            field=models.CharField(db_index=True, default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='imei_full',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
