# Generated by Django 5.2.6 on 2025-09-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_imei_last4_alter_product_imei_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('on_repair', 'on_repair'), ('sold', 'sold')], default='available', max_length=20),
        ),
    ]
