# Generated by Django 5.2.6 on 2025-09-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='product',
            name='document_image',
            field=models.ImageField(blank=True, help_text='Agar hujjat rasmi bo‘lsa, bitta rasm yuklang (ixtiyoriy).', null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_documents',
            field=models.BooleanField(default=False, help_text='Telefonning hujjatlari bor-yo‘qligini belgilang.'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
