# Generated by Django 5.2.7 on 2025-10-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='kind',
            field=models.CharField(blank=True, choices=[('doc', 'Document'), ('cond', 'Condition'), ('other', 'Other')], default='other', max_length=8),
        ),
    ]
