# Generated by Django 5.2.7 on 2025-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_productimage_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ask_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mijozga taklif qilinadigan narx ($)', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimal qabul qilinadigan narx ($)', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amalda sotilgan narx ($)', max_digits=12, null=True),
        ),
    ]
