# Generated by Django 5.2.7 on 2025-10-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_ask_price_product_min_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchintake',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='batchintake',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
