# Generated by Django 5.2.7 on 2025-10-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_batchintake_supplier_name_batchintake_supplier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asking_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
