# Generated by Django 5.2.7 on 2025-10-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_asking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
