# Generated by Django 5.2.7 on 2025-10-14 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0013_product_commission_blocked'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='asking_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='ask_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='commission_blocked',
            field=models.BooleanField(default=False, help_text='Qayta sotishda komissiya berilmaydi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='ownership',
            field=models.CharField(choices=[('owned', "O'zimizniki"), ('consignment', 'Konsignatsiya')], max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Mavjud'), ('on_repair', "Ta'mirda"), ('sold', 'Sotilgan')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='kind',
            field=models.CharField(blank=True, choices=[('doc', 'Hujjat'), ('cond', 'Holat'), ('other', 'Boshqa')], default='other', max_length=8),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['imei_last4'], name='inventory_p_imei_la_7bde03_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'status'], name='inventory_p_store_i_4dbd02_idx'),
        ),
    ]
