# Generated by Django 5.2.6 on 2025-09-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=60)),
                ('entity', models.CharField(max_length=60)),
                ('entity_id', models.CharField(max_length=60)),
                ('before', models.TextField(blank=True)),
                ('after', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
