# Generated by Django 5.2.6 on 2025-09-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_transaction_is_paid_transaction_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercommission',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
