# Generated by Django 5.2.6 on 2025-09-29 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0005_transaction_card_amount_transaction_cash_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sold_by',
            field=models.ForeignKey(blank=True, help_text='Savdo qilgan sotuvchi (kim sotdi)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sold_in_store',
            field=models.ForeignKey(blank=True, help_text="Savdo qaysi do'konda amalga oshirildi (fizik joy)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_on_site', to='accounts.store'),
        ),
    ]
