# Generated by Django 5.2.7 on 2025-10-05 05:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_transaction_sold_by_transaction_sold_in_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(db_index=True, max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['month_key'], name='sales_month_month_k_316847_idx')],
            },
        ),
        migrations.CreateModel(
            name='SellerMonthlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(db_index=True, max_length=7)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('seller', 'month_key')},
            },
        ),
    ]
