# Generated by Django 5.2.7 on 2025-10-05 05:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0007_monthlybonus_sellermonthlystat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='monthlybonus',
            name='sales_month_month_k_316847_idx',
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='category',
            field=models.CharField(default='flat5', max_length=16),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='is_rescinded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='rescinded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='rescinded_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sold_in_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_on_site', to='accounts.store'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
