# Generated by Django 5.2.7 on 2025-10-14 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0014_remove_product_asking_price_alter_product_ask_price_and_more'),
        ('reference', '0001_initial'),
        ('sales', '0008_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sold_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sold_in_store',
        ),
        migrations.AlterField(
            model_name='sellercommission',
            name='category',
            field=models.CharField(choices=[('profit30', '30% foyda'), ('flat5', '$5 fix'), ('none', "Yo'q")], default='flat5', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('sale', 'Sotuv'), ('expense', 'Rashod'), ('debt_out', 'Qarz berish'), ('debt_pay', "Qarz to'lovi"), ('consignment_payout', "Konsignatsiya to'lovi")], max_length=24),
        ),
        migrations.AddIndex(
            model_name='monthlybonus',
            index=models.Index(fields=['month_key'], name='sales_month_month_k_316847_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='sales_notif_recipie_d26723_idx'),
        ),
        migrations.AddIndex(
            model_name='sellermonthlystat',
            index=models.Index(fields=['month_key', '-sales_count'], name='sales_selle_month_k_4af159_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_approved', 'is_void'], name='sales_trans_is_appr_c6504b_idx'),
        ),
    ]
