# Generated by Django 5.2.7 on 2025-10-14 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0014_remove_product_asking_price_alter_product_ask_price_and_more'),
        ('reference', '0001_initial'),
        ('sales', '0009_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercommission',
            name='is_deduction',
            field=models.BooleanField(default=False, help_text='True = bu manfiy komissiya (qaytarish jazosi)'),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='original_commission',
            field=models.ForeignKey(blank=True, help_text="Qaytarish qaysi komissiyaga bog'liq", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions', to='sales.sellercommission'),
        ),
        migrations.AlterField(
            model_name='sellercommission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sellercommission',
            index=models.Index(fields=['seller', 'is_approved'], name='sales_selle_seller__276700_idx'),
        ),
        migrations.AddIndex(
            model_name='sellercommission',
            index=models.Index(fields=['transaction', 'is_deduction'], name='sales_selle_transac_93e749_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller', 'created_at'], name='sales_trans_seller__109113_idx'),
        ),
    ]
