# Generated by Django 5.2.7 on 2025-10-22 16:29

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0014_remove_product_asking_price_alter_product_ask_price_and_more'),
        ('reference', '0001_initial'),
        ('sales', '0010_sellercommission_is_deduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consignmentdue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='monthlybonus',
            options={'ordering': ['-awarded_at']},
        ),
        migrations.AlterModelOptions(
            name='sellercommission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sellermonthlystat',
            options={'ordering': ['-month_key', '-sales_count']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='sales_notif_recipie_d26723_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellercommission',
            name='sales_selle_seller__276700_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='sales_trans_debtor__b4d748_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='sales_trans_is_appr_c6504b_idx',
        ),
        migrations.AddField(
            model_name='consignmentdue',
            name='is_void',
            field=models.BooleanField(default=False, help_text='Bekor qilingan (masalan, qaytarilgan telefon)'),
        ),
        migrations.AddField(
            model_name='consignmentdue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='monthlybonus',
            name='month_key',
            field=models.CharField(db_index=True, help_text='Format: YYYY-MM', max_length=7),
        ),
        migrations.AlterField(
            model_name='sellercommission',
            name='is_deduction',
            field=models.BooleanField(default=False, help_text='True = manfiy komissiya (qaytarish jazosi)'),
        ),
        migrations.AlterField(
            model_name='sellermonthlystat',
            name='month_key',
            field=models.CharField(db_index=True, help_text='Format: YYYY-MM', max_length=7),
        ),
        migrations.AddIndex(
            model_name='consignmentdue',
            index=models.Index(fields=['store', 'is_approved', 'is_void'], name='sales_consi_store_i_77380a_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentdue',
            index=models.Index(fields=['product', 'is_approved'], name='sales_consi_product_7d9b78_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='sales_notif_recipie_c85229_idx'),
        ),
        migrations.AddIndex(
            model_name='sellercommission',
            index=models.Index(fields=['seller', 'is_approved', 'is_paid'], name='sales_selle_seller__65dec4_idx'),
        ),
        migrations.AddIndex(
            model_name='sellercommission',
            index=models.Index(fields=['is_rescinded', 'created_at'], name='sales_selle_is_resc_591f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['debtor_group', 'is_approved'], name='sales_trans_debtor__4348b5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_approved', 'is_void', 'type'], name='sales_trans_is_appr_223c51_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['product', 'type'], name='sales_trans_product_d3f235_idx'),
        ),
    ]
