# Generated by Django 5.2.7 on 2025-11-01 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_store_options_alter_user_options_and_more'),
        ('sales', '0011_alter_consignmentdue_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlybonus',
            name='sales_month_month_k_316847_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellermonthlystat',
            name='sales_selle_month_k_4af159_idx',
        ),
        migrations.AlterUniqueTogether(
            name='sellermonthlystat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlybonus',
            name='store',
            field=models.ForeignKey(default=1, help_text="Qaysi do'kon", on_delete=django.db.models.deletion.CASCADE, to='accounts.store'),
        ),
        migrations.AddField(
            model_name='sellermonthlystat',
            name='store',
            field=models.ForeignKey(default=1, help_text="Qaysi do'kon", on_delete=django.db.models.deletion.CASCADE, to='accounts.store'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybonus',
            unique_together={('store', 'month_key')},
        ),
        migrations.AlterUniqueTogether(
            name='sellermonthlystat',
            unique_together={('seller', 'month_key', 'store')},
        ),
        migrations.AddIndex(
            model_name='monthlybonus',
            index=models.Index(fields=['store', 'month_key'], name='sales_month_store_i_c79f76_idx'),
        ),
        migrations.AddIndex(
            model_name='sellermonthlystat',
            index=models.Index(fields=['store', 'month_key', '-sales_count'], name='sales_selle_store_i_b80a0d_idx'),
        ),
    ]
